import type { GameConfig, SymbolId } from "./types.js";

/** 20 classic fixed paylines on a 5×3 grid (row 0 top, 2 bottom) */
const PAYLINES: number[][] = [
  [1, 1, 1, 1, 1], // mid
  [0, 0, 0, 0, 0], // top
  [2, 2, 2, 2, 2], // bottom
  [0, 1, 2, 1, 0], // V
  [2, 1, 0, 1, 2], // ^
  [0, 0, 1, 2, 2],
  [2, 2, 1, 0, 0],
  [1, 0, 0, 0, 1],
  [1, 2, 2, 2, 1],
  [0, 1, 1, 1, 0],
  [2, 1, 1, 1, 2],
  [1, 0, 1, 2, 1],
  [1, 2, 1, 0, 1],
  [0, 1, 0, 1, 0],
  [2, 1, 2, 1, 2],
  [1, 1, 0, 1, 1],
  [1, 1, 2, 1, 1],
  [0, 0, 1, 0, 0],
  [2, 2, 1, 2, 2],
  [0, 2, 0, 2, 0],
];

function strip(symbols: SymbolId[]): SymbolId[] {
  return symbols;
}

/**
 * Springbok Rush — SA-flavoured demo title.
 * RTP label is illustrative; math is intentionally simple for MVP demos.
 */
export const defaultGameConfig: GameConfig = {
  gameId: "uvaans-slot",
  name: "Uvaan's White Label Slot",
  market: {
    country: "ZA",
    currency: "ZAR",
    localeDefault: "en",
    minAge: 18,
    responsibleGamblingUrl: "https://www.responsiblegambling.org.za/",
    legalFooter:
      "18+ | Demo only — no real-money wagering | Gamble responsibly | Uvaan's Slot",
  },
  branding: {
    logoText: "UVAAN'S DIAMOND SLOT",
    primaryColor: "#D61C24", // Vibrant Ruby Red
    secondaryColor: "#FF2A3B", // Glowing Diamond Red
    accentColor: "#FFFFFF", // Diamond Silver
    backgroundTop: "#1F0306", // Deep Obsidian Black-Red
    backgroundBottom: "#080001", // Pitch Obsidian Black
  },
  layout: {
    reels: 5,
    rows: 3,
    paylineCount: 20,
  },
  betting: {
    startingBalanceCents: 100_000, // R1 000.00 demo
    betStepsCents: [100, 200, 500, 1000, 2000, 5000, 10000], // R1 – R100
    defaultBetCents: 500, // R5
    minBetCents: 100,
    maxBetCents: 10_000,
  },
  features: {
    wild: true,
    scatter: true,
    freeSpins: true,
    freeSpinsTriggerScatters: 3,
    freeSpinsAwarded: 10,
    freeSpinMultiplier: 1,
  },
  rtpLabel: "96.1% (demo math)",
  paytable: [
    {
      symbol: "wild",
      ofAKind: { 3: 10, 4: 50, 5: 200 },
    },
    {
      symbol: "springbok",
      ofAKind: { 3: 5, 4: 20, 5: 100 },
    },
    {
      symbol: "protea",
      ofAKind: { 3: 4, 4: 15, 5: 75 },
    },
    {
      symbol: "gold",
      ofAKind: { 3: 3, 4: 12, 5: 50 },
    },
    {
      symbol: "drum",
      ofAKind: { 3: 2, 4: 8, 5: 30 },
    },
    {
      symbol: "A",
      ofAKind: { 3: 1, 4: 4, 5: 15 },
    },
    {
      symbol: "K",
      ofAKind: { 3: 1, 4: 3, 5: 12 },
    },
    {
      symbol: "Q",
      ofAKind: { 3: 0.8, 4: 2.5, 5: 10 },
    },
    {
      symbol: "J",
      ofAKind: { 3: 0.6, 4: 2, 5: 8 },
    },
    {
      symbol: "10",
      ofAKind: { 3: 0.5, 4: 1.5, 5: 6 },
    },
  ],
  reelStrips: [
    strip([
      "10",
      "J",
      "Q",
      "springbok",
      "K",
      "A",
      "drum",
      "10",
      "wild",
      "J",
      "protea",
      "Q",
      "gold",
      "K",
      "scatter",
      "A",
      "10",
      "drum",
      "J",
      "springbok",
      "Q",
      "K",
      "gold",
      "A",
      "10",
      "protea",
      "J",
      "Q",
      "drum",
      "K",
    ]),
    strip([
      "J",
      "10",
      "gold",
      "Q",
      "A",
      "springbok",
      "K",
      "10",
      "drum",
      "J",
      "wild",
      "Q",
      "protea",
      "K",
      "A",
      "scatter",
      "10",
      "J",
      "drum",
      "Q",
      "gold",
      "K",
      "springbok",
      "A",
      "10",
      "J",
      "protea",
      "Q",
      "K",
      "A",
    ]),
    strip([
      "Q",
      "K",
      "10",
      "protea",
      "J",
      "A",
      "drum",
      "Q",
      "springbok",
      "K",
      "10",
      "wild",
      "J",
      "gold",
      "A",
      "scatter",
      "Q",
      "K",
      "drum",
      "10",
      "J",
      "protea",
      "A",
      "Q",
      "springbok",
      "K",
      "10",
      "gold",
      "J",
      "A",
    ]),
    strip([
      "A",
      "10",
      "J",
      "drum",
      "Q",
      "gold",
      "K",
      "springbok",
      "10",
      "J",
      "wild",
      "Q",
      "A",
      "protea",
      "K",
      "scatter",
      "10",
      "drum",
      "J",
      "Q",
      "gold",
      "A",
      "K",
      "10",
      "springbok",
      "J",
      "protea",
      "Q",
      "A",
      "K",
    ]),
    strip([
      "10",
      "Q",
      "K",
      "A",
      "springbok",
      "J",
      "drum",
      "10",
      "gold",
      "Q",
      "wild",
      "K",
      "protea",
      "A",
      "J",
      "scatter",
      "10",
      "Q",
      "drum",
      "K",
      "springbok",
      "A",
      "J",
      "gold",
      "10",
      "Q",
      "protea",
      "K",
      "A",
      "J",
    ]),
  ],
  paylines: PAYLINES,
  embed: {
    allowIframe: true,
    demoOnly: true,
  },
};
